#!/bin/bash
dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

html_file=explorer.html

function parse()
{
    full_path=$1
    dir_name=$(dirname ${full_path})

    echo "<strong><a href=\"./api/${dir_name}/\">${dir_name}</a></strong>" >> ${dir}/${html_file}

    desc=()
    params=()

    while IFS= read line; do
        if [[ $line = '//*'* ]]; then
            if [[ $line = '//*desc:'* ]]; then
                desc+="<div>${line:9}</div>" >> ${dir}/${html_file}
            else
                params+="<li>${line:3}</li>" >> ${dir}/${html_file}
            fi
        fi
    done <"${full_path}"

    for d in "${desc[@]}"; do
        echo $d >> ${dir}/${html_file}
    done

    echo "<ul>" >> ${dir}/${html_file}

    for p in "${params[@]}"; do
        echo $p >> ${dir}/${html_file}
    done

    echo "</ul>" >> ${dir}/${html_file}
}

function section()
{
    name=$1
    name_lower=$(echo "${name}" | tr '[:upper:]' '[:lower:]')

    echo "<div class=\"row well bs-component\">"    >> ${dir}/${html_file}
    echo "<form class=\"form-horizontal\">"         >> ${dir}/${html_file}
    echo "<fieldset>"                               >> ${dir}/${html_file}
    echo "<div class=\"col-md-12\">"                >> ${dir}/${html_file}
    echo "<div class=\"form-group\">"               >> ${dir}/${html_file}

    echo "<h4>${name}</h4>"          >> ${dir}/${html_file}
    echo "<div>"                                    >> ${dir}/${html_file}

    cd ${dir}/${name_lower}
    files=($(find . -name *.php))
    cd ${dir}

    for fn in "${files[@]}"; do
        file="${name_lower}/${fn:2:${#fn}}"
        parse ${file}
    done

    echo "</ul>" >> ${dir}/${html_file}
    echo "</div>" >> ${dir}/${html_file}
    echo "</div>" >> ${dir}/${html_file}
    echo "</div>" >> ${dir}/${html_file}
    echo "</fieldset>" >> ${dir}/${html_file}
    echo "</form>" >> ${dir}/${html_file}
    echo "</div>" >> ${dir}/${html_file}
}

echo > ${dir}/${html_file}

section Daemon
section Wallet
section External
section Analytics