#!/bin/bash
dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

function parse()
{
    full_path=$1
    dir_name=$(dirname ${full_path})
    echo "<a href=\"./${dir_name}/\">${dir_name}</a>" >> ${dir}/index.html
    
    while IFS= read line; do
        if [[ $line = '//*'* ]]; then
            if [[ $line = '//*desc:'* ]]; then
                echo ${line:9} >> ${dir}/index.html
            else
                echo "   " ${line:3} >> ${dir}/index.html
            fi
        fi
    done <"${full_path}"
    
    echo "" >> ${dir}/index.html
}

function section()
{
    name=$1
    name_lower=$(echo "${name}" | tr '[:upper:]' '[:lower:]')

    echo "<pre><h4>${name}</h4><ul>" >> ${dir}/index.html

    cd ${dir}/${name_lower}
    files=($(find . -name *.php))
    cd ${dir}

    for fn in "${files[@]}"; do
        file="${name_lower}/${fn:2:${#fn}}"
        parse ${file}
    done

    echo "</ul></pre>" >> ${dir}/index.html
}

echo "<pre><h3>NERVA Public API</h3></pre>" > ${dir}/index.html
section Daemon
section Wallet
section External
section Analytics